const DB_NAME='mgp-daily-db', DB_VERSION=1;
const priorityMeta={emergency:{label:'Emergência',weight:4,tone:'danger'},high:{label:'Alta',weight:3,tone:'warning'},medium:{label:'Média',weight:2,tone:'info'},low:{label:'Baixa',weight:1,tone:'neutral'}};
const statusMeta={planned:'Planejada',inProgress:'Em execução',interrupted:'Interrompida',waitingMaterial:'Aguardando material',waitingEnvironment:'Aguardando ambiente',saturday:'Sábado',completed:'Concluída'};
const categories=['Elétrica','Hidráulica','Pintura','Civil','Gesso','Marcenaria','Inspeção','Preventiva','Outro'];
const interruptionReasons=['Solicitação da gestão','Emergência','Falta de material','Ambiente ocupado','Terceiro','Fim do expediente','Outro'];
const state={tab:'today',tasks:[],materials:[]};
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const now=()=>new Date().toISOString();

function openDb(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const db=r.result;for(const s of ['tasks','materials'])if(!db.objectStoreNames.contains(s))db.createObjectStore(s,{keyPath:'id'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function all(store){const db=await openDb();return new Promise((res,rej)=>{const r=db.transaction(store,'readonly').objectStore(store).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
async function put(store,val){const db=await openDb();return new Promise((res,rej)=>{const tx=db.transaction(store,'readwrite');tx.objectStore(store).put(val);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}
async function del(store,id){const db=await openDb();return new Promise((res,rej)=>{const tx=db.transaction(store,'readwrite');tx.objectStore(store).delete(id);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}
async function clear(store){const db=await openDb();return new Promise((res,rej)=>{const tx=db.transaction(store,'readwrite');tx.objectStore(store).clear();tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}
async function refresh(){state.tasks=await all('tasks');state.materials=await all('materials');render()}
function active(){return state.tasks.filter(t=>t.status!=='completed')}
function executable(){return active().filter(t=>['planned','interrupted','inProgress'].includes(t.status)).sort((a,b)=>a.status==='inProgress'?-1:b.status==='inProgress'?1:priorityMeta[b.priority].weight-priorityMeta[a.priority].weight||new Date(a.createdAt)-new Date(b.createdAt))}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(msg){let t=document.querySelector('.toast');if(t)t.remove();t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),2400)}
function stat(v,l,t=''){return `<div class="stat ${t}"><strong>${v}</strong><span>${l}</span></div>`}
function empty(title,text){return `<div class="empty"><div class="empty-icon">✓</div><strong>${title}</strong><span>${text}</span></div>`}

function card(t,{deleteButton=false}={}){const pm=priorityMeta[t.priority];return `<article class="task-card ${t.status==='inProgress'?'featured':''}">
<div class="task-top"><div><div class="badge-row"><span class="priority-badge ${pm.tone}">${pm.label}</span><span class="status-badge">${statusMeta[t.status]}</span></div><h3>${esc(t.title)}</h3><p>${esc(t.location)} · ${esc(t.category)} · ${t.estimatedMinutes} min</p>${t.interruptionReason?`<p class="reason">Motivo: ${esc(t.interruptionReason)}</p>`:''}</div><button class="kebab" data-edit="${t.id}">•••</button></div>
<div class="task-actions">
${t.status!=='inProgress'&&t.status!=='completed'?`<button class="primary-btn" data-start="${t.id}">▶ ${t.status==='interrupted'?'Retomar':'Iniciar'}</button>`:''}
${t.status==='inProgress'?`<button class="secondary-btn" data-interrupt="${t.id}">Pausar</button><button class="success-btn" data-complete="${t.id}">Concluir</button>`:''}
${!['completed','waitingMaterial'].includes(t.status)?`<button class="text-btn" data-block="waitingMaterial:${t.id}">Falta material</button>`:''}
${!['completed','waitingEnvironment'].includes(t.status)?`<button class="text-btn" data-block="waitingEnvironment:${t.id}">Ambiente ocupado</button>`:''}
${!['completed','saturday'].includes(t.status)?`<button class="text-btn" data-block="saturday:${t.id}">Sábado</button>`:''}
${t.status!=='completed'&&t.status!=='inProgress'?`<button class="text-btn success-text" data-complete="${t.id}">Concluir</button>`:''}
${deleteButton?`<button class="text-btn danger-text" data-delete="${t.id}">Excluir</button>`:''}
</div></article>`}

function todayView(){const a=active(), ex=executable(), next=ex[0], interrupted=a.filter(t=>t.status==='interrupted'), blocked=a.filter(t=>['waitingMaterial','waitingEnvironment'].includes(t.status));return `<section class="hero"><p class="muted">Controle primeiro o que realmente pode e deve ser feito.</p><div class="stats-grid">${stat(a.filter(t=>t.priority==='emergency').length,'Emergências','danger')}${stat(a.filter(t=>t.priority==='high').length,'Alta prioridade','warning')}${stat(interrupted.length,'Interrompidas','violet')}${stat(a.filter(t=>t.status==='waitingMaterial').length,'Sem material')}</div></section>
<section class="section"><div class="section-head"><div><span class="eyebrow">PRÓXIMA MISSÃO</span><h2>O que fazer agora</h2></div></div>${next?card(next):empty('Nenhuma tarefa executável','Cadastre uma tarefa ou revise as atividades bloqueadas.')}</section>
${interrupted.length?`<section class="section"><div class="section-head"><h2>Retomar</h2><span class="count-pill">${interrupted.length}</span></div>${interrupted.slice(0,3).map(t=>card(t)).join('')}</section>`:''}
${blocked.length?`<section class="section"><div class="section-head"><h2>Bloqueadas</h2><span class="count-pill">${blocked.length}</span></div>${blocked.slice(0,3).map(t=>card(t)).join('')}</section>`:''}`}
function tasksView(){const sorted=[...state.tasks].sort((a,b)=>priorityMeta[b.priority].weight-priorityMeta[a.priority].weight||new Date(a.createdAt)-new Date(b.createdAt));return `<section class="section flush"><div class="filter-row"><button class="chip selected">Todas</button><button class="chip">Ativas: ${active().length}</button><button class="chip">Concluídas: ${state.tasks.filter(t=>t.status==='completed').length}</button></div>${sorted.length?sorted.map(t=>card(t,{deleteButton:true})).join(''):empty('Sem tarefas','Crie sua primeira tarefa usando o botão +.')}</section>`}
function saturdayView(){const ts=state.tasks.filter(t=>t.status==='saturday');return `<section class="section flush"><div class="notice"><div><strong>Janela protegida</strong><span>Use o sábado para serviços que exigem ambiente desocupado, ruído ou bloqueio de área.</span></div></div>${ts.length?ts.map(t=>card(t)).join(''):empty('Sábado livre','Nenhuma tarefa está programada para sábado.')}</section>`}
function materialState(m){return m.quantity<=0?'out':m.quantity<=m.minimum?'low':'ok'}
function materialsView(){const ms=[...state.materials].sort((a,b)=>({out:0,low:1,ok:2}[materialState(a)]-({out:0,low:1,ok:2}[materialState(b)])));return `<section class="section flush"><div class="section-head"><div><span class="eyebrow">ESTOQUE OPERACIONAL</span><h2>Essenciais</h2></div><button class="secondary-btn" id="newMaterial">＋ Material</button></div><div class="material-summary">${stat(ms.filter(m=>materialState(m)==='out').length,'Acabou','danger')}${stat(ms.filter(m=>materialState(m)==='low').length,'Baixo','warning')}${stat(ms.filter(m=>materialState(m)==='ok').length,'OK','success')}</div>${ms.length?ms.map(m=>`<div class="material-card"><div><strong>${esc(m.name)}</strong><span>${m.quantity} ${esc(m.unit)} · mínimo ${m.minimum}</span></div><div class="material-actions"><span class="stock-badge ${materialState(m)}">${materialState(m)==='out'?'Acabou':materialState(m)==='low'?'Baixo':'OK'}</span><button class="text-btn" data-edit-material="${m.id}">Editar</button></div></div>`).join(''):empty('Sem materiais cadastrados','Cadastre somente os itens essenciais que você precisa acompanhar.')}</section>`}
function historyView(){const events=state.tasks.flatMap(t=>(t.history||[]).map(h=>({...h,task:t.title,location:t.location}))).sort((a,b)=>new Date(b.at)-new Date(a.at));return `<section class="section flush"><div class="backup-box"><div><strong>Backup local</strong><span>Os dados desta versão ficam neste navegador. Exporte um backup periodicamente.</span></div><div class="backup-actions"><button class="secondary-btn" id="exportBtn">Exportar</button><button class="secondary-btn" id="importBtn">Importar</button></div></div><div class="section-head"><h2>Atividade recente</h2></div>${events.length?events.slice(0,60).map(e=>`<div class="history-row"><div class="timeline-dot"></div><div><strong>${esc(e.action)}</strong><span>${esc(e.task)} · ${esc(e.location)}</span><small>${new Date(e.at).toLocaleString('pt-BR')}</small></div></div>`).join(''):empty('Sem histórico','As movimentações das tarefas aparecerão aqui.')}</section>`}

function render(){const titles={today:'Minha Jornada',tasks:'Tarefas',saturday:'Sábado',materials:'Materiais',history:'Histórico'};document.querySelector('#app').innerHTML=`<div class="app-shell"><header class="topbar"><div><div class="eyebrow">MGP Daily <span class="version">v0.1.0</span></div><h1>${titles[state.tab]}</h1></div><button class="icon-btn" id="newTask">＋</button></header><main class="content">${state.tab==='today'?todayView():state.tab==='tasks'?tasksView():state.tab==='saturday'?saturdayView():state.tab==='materials'?materialsView():historyView()}</main><nav class="bottom-nav">${[['today','⌂','Hoje'],['tasks','☷','Tarefas'],['saturday','◷','Sábado'],['materials','▣','Materiais'],['history','↺','Histórico']].map(([v,i,l])=>`<button class="nav-btn ${state.tab===v?'active':''}" data-tab="${v}"><span class="nav-icon">${i}</span><span>${l}</span></button>`).join('')}</nav></div>`;bind()}
function bind(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render()});document.querySelector('#newTask')?.addEventListener('click',()=>taskModal());document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>taskModal(state.tasks.find(t=>t.id===b.dataset.edit)));document.querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>startTask(b.dataset.start));document.querySelectorAll('[data-interrupt]').forEach(b=>b.onclick=()=>interruptTask(b.dataset.interrupt));document.querySelectorAll('[data-complete]').forEach(b=>b.onclick=()=>transition(b.dataset.complete,'completed','Tarefa concluída',{completedAt:now(),interruptionReason:''}));document.querySelectorAll('[data-block]').forEach(b=>b.onclick=()=>{const[s,id]=b.dataset.block.split(':');transition(id,s,s==='waitingMaterial'?'Aguardando material':s==='waitingEnvironment'?'Aguardando ambiente':'Programada para sábado')});document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{const t=state.tasks.find(x=>x.id===b.dataset.delete);if(confirm(`Excluir "${t.title}"?`)){await del('tasks',t.id);refresh()}});document.querySelector('#newMaterial')?.addEventListener('click',()=>materialModal());document.querySelectorAll('[data-edit-material]').forEach(b=>b.onclick=()=>materialModal(state.materials.find(m=>m.id===b.dataset.editMaterial)));document.querySelector('#exportBtn')?.addEventListener('click',exportBackup);document.querySelector('#importBtn')?.addEventListener('click',importBackup)}

async function transition(id,status,action,extra={}){const t=state.tasks.find(x=>x.id===id);if(!t)return;await put('tasks',{...t,...extra,status,updatedAt:now(),history:[...(t.history||[]),{at:now(),action}]});await refresh()}
async function startTask(id){const t=state.tasks.find(x=>x.id===id);const running=state.tasks.find(x=>x.status==='inProgress'&&x.id!==id);if(running)await put('tasks',{...running,status:'interrupted',interruptionReason:'Troca de prioridade',updatedAt:now(),history:[...(running.history||[]),{at:now(),action:`Interrompida automaticamente para iniciar: ${t.title}`}]});await transition(id,'inProgress','Execução iniciada',{startedAt:t.startedAt||now(),interruptionReason:''})}
async function interruptTask(id){const reason=prompt(`Motivo da interrupção:\n${interruptionReasons.join('\n')}`,'Solicitação da gestão');if(reason)await transition(id,'interrupted',`Interrompida: ${reason}`,{interruptionReason:reason})}

function modalShell(inner){const el=document.createElement('div');el.className='modal-backdrop';el.innerHTML=inner;el.addEventListener('mousedown',e=>{if(e.target===el)el.remove()});document.body.appendChild(el);return el}
function taskModal(task){const el=modalShell(`<form class="modal"><div class="modal-head"><div><span class="eyebrow">${task?'EDITAR':'NOVA'}</span><h2>${task?'Tarefa':'Nova tarefa'}</h2></div><button type="button" class="icon-btn subtle close">×</button></div><label>Título<input name="title" required value="${esc(task?.title||'')}" placeholder="Ex.: Trocar luminária"></label><label>Local<input name="location" required value="${esc(task?.location||'')}" placeholder="Ex.: Biblioteca"></label><div class="form-grid"><label>Categoria<select name="category">${categories.map(c=>`<option ${task?.category===c?'selected':''}>${c}</option>`).join('')}</select></label><label>Prioridade<select name="priority">${Object.entries(priorityMeta).map(([v,m])=>`<option value="${v}" ${(task?.priority||'medium')===v?'selected':''}>${m.label}</option>`).join('')}</select></label></div><label>Tempo estimado (min)<input name="estimatedMinutes" type="number" min="1" value="${task?.estimatedMinutes||20}"></label><label>Observação<textarea name="notes" rows="3" placeholder="Detalhes úteis para retomar depois...">${esc(task?.notes||'')}</textarea></label><div class="modal-actions"><button type="button" class="secondary-btn close">Cancelar</button><button class="primary-btn">Salvar tarefa</button></div></form>`);el.querySelectorAll('.close').forEach(b=>b.onclick=()=>el.remove());el.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const existing=task||{};const val={id:task?.id||uid(),title:f.get('title').trim(),location:f.get('location').trim(),category:f.get('category'),priority:f.get('priority'),estimatedMinutes:Number(f.get('estimatedMinutes'))||15,notes:f.get('notes').trim(),status:existing.status||'planned',createdAt:existing.createdAt||now(),updatedAt:now(),history:existing.history||[{at:now(),action:'Tarefa criada'}],interruptionReason:existing.interruptionReason||''};await put('tasks',val);el.remove();await refresh();toast(task?'Tarefa atualizada.':'Tarefa criada.')}}
function materialModal(material){const el=modalShell(`<form class="modal small"><div class="modal-head"><div><span class="eyebrow">ESTOQUE</span><h2>${material?'Editar material':'Novo material'}</h2></div><button type="button" class="icon-btn subtle close">×</button></div><label>Material<input name="name" required value="${esc(material?.name||'')}" placeholder="Ex.: Lâmpada LED 18W"></label><div class="form-grid"><label>Quantidade<input name="quantity" type="number" min="0" value="${material?.quantity||0}"></label><label>Mínimo<input name="minimum" type="number" min="0" value="${material?.minimum||0}"></label></div><label>Unidade<select name="unit">${['un','m','kg','L','cx','pct'].map(u=>`<option ${material?.unit===u?'selected':''}>${u}</option>`).join('')}</select></label><div class="modal-actions"><button type="button" class="secondary-btn close">Cancelar</button><button class="primary-btn">Salvar</button></div></form>`);el.querySelectorAll('.close').forEach(b=>b.onclick=()=>el.remove());el.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);await put('materials',{id:material?.id||uid(),name:f.get('name').trim(),quantity:Number(f.get('quantity'))||0,minimum:Number(f.get('minimum'))||0,unit:f.get('unit'),createdAt:material?.createdAt||now(),updatedAt:now()});el.remove();await refresh();toast(material?'Material atualizado.':'Material adicionado.')}}
async function exportBackup(){const data={version:'0.1.0',exportedAt:now(),tasks:state.tasks,materials:state.materials};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=`mgp-daily-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importBackup(){const i=document.createElement('input');i.type='file';i.accept='application/json';i.onchange=async()=>{try{const data=JSON.parse(await i.files[0].text());if(!Array.isArray(data.tasks)||!Array.isArray(data.materials))throw new Error();await clear('tasks');await clear('materials');for(const t of data.tasks)await put('tasks',t);for(const m of data.materials)await put('materials',m);await refresh();toast('Backup restaurado.')}catch{alert('Arquivo de backup inválido.')}};i.click()}

if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.error));
refresh();
